# Generated by Django 5.2 on 2025-05-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_userprofile_otp_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=16)),
                ('mfa_secret', models.TextField(blank=True, null=True)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CynaAddresses',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=8)),
                ('street', models.CharField(max_length=64)),
                ('complement', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=64)),
                ('postal_code', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'cyna_addresses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CynaCards',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=16)),
                ('expiration', models.DateField()),
                ('last_name', models.CharField(max_length=16)),
                ('first_name', models.CharField(max_length=16)),
                ('ccv', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'cyna_cards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CynaCardTypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, unique=True)),
                ('description', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'cyna_card_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CynaCountries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=48, unique=True)),
            ],
            options={
                'db_table': 'cyna_countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CynaOrderFulfillment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, unique=True)),
                ('description', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'cyna_order_fulfillment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CynaOrders',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateTimeField()),
                ('is_renewed', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'cyna_orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CynaRelUserCard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cyna_rel_user_card',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
