# Generated by Django 5.2 on 2025-05-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_authuser_cynaaddresses_cynacards_cynacardtypes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cynaaddresses',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cynacards',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cynacardtypes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cynacountries',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cynaorderfulfillment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cynaorders',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cynarelusercard',
            options={'managed': True},
        ),
    ]
