# Generated by Django 5.2 on 2025-05-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_cynaaddresses_options_alter_cynacards_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cynaaddresses',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cynacards',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cynacardtypes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cynacountries',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cynaorderfulfillment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cynaorders',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cynarelusercard',
            options={'managed': False},
        ),
    ]
