# Generated by Django 5.2 on 2025-05-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CynaDiscounts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField()),
                ('expiration', models.DateField()),
            ],
            options={
                'db_table': 'cyna_discounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CynaProductCategories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=24, unique=True)),
                ('description', models.CharField(blank=True, max_length=48, null=True)),
            ],
            options={
                'db_table': 'cyna_product_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CynaProducts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=24, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'cyna_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CynaRenewalIntervals',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('days', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'cyna_renewal_intervals',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
