# Generated by Django 5.2 on 2025-05-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_cynadiscounts_cynaproductcategories_cynaproducts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cynadiscounts',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cynaproductcategories',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cynaproducts',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cynarenewalintervals',
            options={'managed': True},
        ),
    ]
