# Generated by Django 5.2 on 2025-05-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_cynadiscounts_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cynadiscounts',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cynaproductcategories',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cynaproducts',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cynarenewalintervals',
            options={'managed': False},
        ),
    ]
